version: "3.2"

services:
  adminer:
    container_name: adminer
    build:
      context: ${HUNCHO_DIR}/services/adminer
      dockerfile: ${HUNCHO_DIR}/services/adminer/build/Dockerfile
    restart: always
    ports:
      - 8080:8080
  score:
    container_name: score
    build:
      context: ${HUNCHO_DIR}/services/score
      dockerfile: ${HUNCHO_DIR}/services/score/build/Dockerfile
    restart: on-failure
    volumes:
      - ${HUNCHO_DIR}/services/score/migrations:/home/app/migrations
      - ${HUNCHO_DIR}/services/score/bin:/home/app/bin
      - ${HUNCHO_DIR}/services/score/tests:/home/app/tests
      - ${HUNCHO_DIR}/services/score/seeds:/home/app/seeds
      - ${HUNCHO_DIR}/services/score/src:/home/app/src
      - ${HUNCHO_DIR}/services/score/statics:/home/app/statics
      - ${HUNCHO_DIR}/services/score/manage.py:/home/app/manage.py
      - ${HUNCHO_DIR}/services/score/setup.py:/home/app/setup.py
    env_file:
      - ${HUNCHO_DIR}/env/dev/.env.score
    healthcheck:
      test: curl --fail -s score:5000/ping || exit 1
      interval: 60s
      timeout: 5s
      retries: 5
    depends_on:
      - score_cache
      - score_db
  score_cache:
    container_name: score_cache
    build:
      context: ${HUNCHO_DIR}/services/redis
      dockerfile: ${HUNCHO_DIR}/services/redis/build/Dockerfile
    restart: unless-stopped
    volumes:
      - ${HUNCHO_DIR}/data/dev/score_cache/redis_data:/var/lib/redis
      - ${HUNCHO_DIR}/data/dev/score_cache/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - ${HUNCHO_DIR}/env/dev/.env.score_cache
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  score_db:
    container_name: score_db
    build:
      context: ${HUNCHO_DIR}/services/postgresql
      dockerfile: ${HUNCHO_DIR}/services/postgresql/build/Dockerfile
      args:
        POSTGRES_VERSION: 9.6
    volumes:
      - ${HUNCHO_DIR}/data/dev/score_db/data:/var/lib/postgresql/data/
    env_file:
      - ${HUNCHO_DIR}/env/dev/.env.score_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U score"]
      interval: 10s
      timeout: 5s
      retries: 20
  score_proxy:
    container_name: score_proxy
    build:
      context: ${HUNCHO_DIR}/services/score/proxy
      dockerfile: ${HUNCHO_DIR}/services/score/proxy/build/Dockerfile
    restart: on-failure
    volumes:
      - ${HUNCHO_DIR}/services/score/statics/.:/usr/share/nginx/
    ports:
      - 80:80
    depends_on:
      - score