version: '3.2'

services:
    score:
        container_name: score
        build:
            context: .
            dockerfile: build/Dockerfile
            args:
                NODE_VERSION: 12
        restart: on-failure
        volumes:
            - ${HUNCHO_DIR}/services/score/src:/home/app/src
            - ${HUNCHO_DIR}/services/score/test:/home/app/test
            - ${HUNCHO_DIR}/services/score/package.json:/home/app/package.json
        env_file:
            - env/.env.score
        healthcheck:
            test: curl --fail -s score:3000/ping || exit 1
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - 20005:3000
        depends_on:
            - score_mongodb
        networks:
            - app-net
    score_mongodb:
        container_name: score_mongodb
        image: mongo:3.6
        volumes:
            - mongo_data:/data/db
            - mongo_home:/home/mongodb # this must be manually created and chown'd to 999 https://github.com/docker-library/mongo/issues/323
            - ${HUNCHO_DIR}/services/score/bin/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
            - ${HUNCHO_DIR}/services/score/bin/reset-mongo.sh:/bin/reset-mongo.sh
        env_file:
            - env/.env.score_mongodb
        networks:
            - app-net
    score_kafka:
        container_name: score_kafka
        image: wurstmeister/kafka:latest
        restart: on-failure
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
            - env/.env.score_kafka
        depends_on:
            - score_zookeeper
        networks:
            - app-net
    score_zookeeper:
        container_name: score_zookeeper
        image: wurstmeister/zookeeper:latest
        restart: on-failure
        env_file:
            - env/.env.score_zookeeper
        networks:
            - app-net
    mongo-express:
        container_name: mongo-express
        image: mongo-express:latest
        restart: always
        ports:
            - 8081:8081
        env_file:
            - env/.env.score_mongo-express
        networks:
            - app-net
volumes:
    mongo_data:
    mongo_home:
networks:
    app-net:
        driver: bridge
