version: "3.2"

services:
  score:
    container_name: score
    build:
      context: ${HUNCHO_DIR}/services/score
      dockerfile: ${HUNCHO_DIR}/services/score/build/Dockerfile.qaw
      args:
        NODE_VERSION: 12
    restart: on-failure
    volumes:
      - ${HUNCHO_DIR}/services/score/src:/home/app/src
    env_file:
      - ${HUNCHO_DIR}/env/qaw/.env.score
    healthcheck:
      test: curl --fail -s score:3000/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
#      - score_cache
      - score_mongodb
    networks:
      - score-net
#  score_cache:
#    container_name: score_cache
#    build:
#      context: ${HUNCHO_DIR}/services/redis
#      dockerfile: ${HUNCHO_DIR}/services/redis/build/Dockerfile
#    restart: unless-stopped
#    volumes:
#      - ${HUNCHO_DIR}/data/qaw/score_cache/redis_data:/var/lib/redis
#      - ${HUNCHO_DIR}/data/qaw/score_cache/redis.conf:/usr/local/etc/redis/redis.conf
#    env_file:
#      - ${HUNCHO_DIR}/env/qaw/.env.score_cache
#    healthcheck:
#      test: ["CMD", "redis-cli","ping"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
  score_mongodb:
    container_name: score_mongodb
    image: mongo:3.6
    volumes:
      - ${HUNCHO_DIR}/data/qaw/score_mongodb/data:/data/db
      - ${HUNCHO_DIR}/data/qaw/score_home:/home/mongodb # this must be manually created and chown'd to 999 https://github.com/docker-library/mongo/issues/323
      - ${HUNCHO_DIR}/build/bin/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ${HUNCHO_DIR}/build/bin/reset-mongo.sh:/bin/reset-mongo.sh
    env_file:
      - ${HUNCHO_DIR}/env/qaw/.env.score_mongodb
    networks:
      - score-net
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ${HUNCHO_DIR}/env/qaw/.env.score-mongo-express
    networks:
      - score-net
networks:
    score-net:
        driver: bridge
