version: "3.2"

services:
  score:
    container_name: score
    build:
      context: ${HUNCHO_DIR}/services/score
      dockerfile: ${HUNCHO_DIR}/services/score/build/Dockerfile
      args:
        NODE_VERSION: 12
    restart: on-failure
    volumes:
      - ${HUNCHO_DIR}/services/score/src:/home/app/src
    env_file:
      - ${HUNCHO_DIR}/env/dev/.env.score
    healthcheck:
      test: curl --fail -s score:3000/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 20005:3000
    depends_on:
      - score_mongodb
    networks:
      - app-net
  score_mongodb:
    container_name: score_mongodb
    image: mongo:3.6
    volumes:
      - ${HUNCHO_DIR}/data/dev/score_mongodb/data:/data/db
      - ${HUNCHO_DIR}/data/dev/score_home:/home/mongodb # this must be manually created and chown'd to 999 https://github.com/docker-library/mongo/issues/323
      - ${HUNCHO_DIR}/build/bin/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    env_file:
      - ${HUNCHO_DIR}/env/dev/.env.score_mongodb
    networks:
      - app-net
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ${HUNCHO_DIR}/env/dev/.env.score-mongo-express
    networks:
      - app-net
networks:
  app-net:
    driver: bridge
