version: "3.2"

services:
  score:
    container_name: score
    build:
      context: ${HUNCHO_DIR}/services/score
      dockerfile: ${HUNCHO_DIR}/services/score/build/Dockerfile
    restart: on-failure
    volumes:
      - ${HUNCHO_DIR}/services/score/migrations:/home/app/migrations
      - ${HUNCHO_DIR}/services/score/bin:/home/app/bin
      - ${HUNCHO_DIR}/services/score/tests:/home/app/tests
      - ${HUNCHO_DIR}/services/score/seeds:/home/app/seeds
      - ${HUNCHO_DIR}/services/score/src:/home/app/src
      - ${HUNCHO_DIR}/services/score/statics:/home/app/statics
      - ${HUNCHO_DIR}/services/score/manage.py:/home/app/manage.py
      - ${HUNCHO_DIR}/services/score/setup.py:/home/app/setup.py
    env_file:
      - ${HUNCHO_DIR}/env/dev/.env.score
    healthcheck:
      test: curl --fail -s score:5000/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5000:5000
    depends_on:
#      - score_cache
      - score_db
      - score_mongodb
    networks:
      - score-net
      - kong-net
#  score_cache:
#    container_name: score_cache
#    build:
#      context: ${HUNCHO_DIR}/services/redis
#      dockerfile: ${HUNCHO_DIR}/services/redis/build/Dockerfile
#    restart: unless-stopped
#    volumes:
#      - ${HUNCHO_DIR}/data/dev/score_cache/redis_data:/var/lib/redis
#      - ${HUNCHO_DIR}/data/dev/score_cache/redis.conf:/usr/local/etc/redis/redis.conf
#    env_file:
#      - ${HUNCHO_DIR}/env/dev/.env.score_cache
#    healthcheck:
#      test: ["CMD", "redis-cli","ping"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
  score_db:
    container_name: score_db
    image: postgres:9.6
    volumes:
      - ${HUNCHO_DIR}/data/dev/score_db/data:/var/lib/postgresql/data/
    env_file:
      - ${HUNCHO_DIR}/env/dev/.env.score_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U score"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - score-net
  score_mongodb:
    container_name: score_mongodb
    image: mongo:3.6
    volumes:
      - ${HUNCHO_DIR}/data/dev/score_mongodb/data:/data/db
      - ${HUNCHO_DIR}/data/dev/score_home:/home/mongodb # this must be manually created and chown'd to 999 https://github.com/docker-library/mongo/issues/323
      - ${HUNCHO_DIR}/build/bin/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    env_file:
      - ${HUNCHO_DIR}/env/dev/.env.score_mongodb
    networks:
      - score-net
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - score-net
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ${HUNCHO_DIR}/env/dev/.env.score-mongo-express
    networks:
      - score-net
networks:
    score-net:
        driver: bridge
    kong-net:
      external:
        name: frontend_kong-net